application: pictoricalmap
version: 0-1-dev
runtime: python
api_version: 1

handlers:
- url: /
  upload: content/index.html
  static_files: content/index.html

- url: /blacklist.*
  script: python/blacklist.py

- url: /(.*\.(css|js))
  expiration: "365d"
  upload: .*\.(css|js)
  static_files: \1
 
- url: /(\w+)/?
  upload: content/.*\.html
  static_files: content/\1.html